name: blog
version: '0.1.0.0'
category: Web
author: Chris Penner
maintainer: christopher.penner@gmail.com
copyright: 2017 Chris Penner
license: BSD3
homepage: https://github.com/ChrisPenner/my-blog-sitepipe#readme
extra-source-files:
- README.md
ghc-options:
- -threaded
- -rtsopts
- -with-rtsopts=-N
- -Wall
dependencies:
- base
- slick >=1.2.0.0
- shake
- text
- mustache >=2.2.3
- lens
- time
- aeson
- lens-aeson
- pandoc
- binary
- bytestring
- containers

executables:
  build-site:
    main: Main.hs
    source-dirs: app
